
sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  api_key:
    secure: XyNC/Hjn8TwzgcP0PpDrEiFWLDtH6Rh6SGBmLI9g3gXOaX3ZByBkK1iYS6WffdfkSUm5EHDDqJHGxCV4nNM/s0m/1+x1p91aCiORvTIM+k5VhR+5zWKV44HuOsbv1pLlC1il2xQbQVvSJy1bldgUZC0c8UiP3fZqzFhoGJm68hoThheC1qvXDuL1QHCrPWJ3w7DCZ4O6H45qF+uqEdsWW4p6JlPUR7uzPDMvsMNVjZQomLFtweCZgIyi6FyQySWeLTLyCBxEqGrz2oNhkF9SCGMwv1gE10pmxN44WOphy3aZR3gH/M66joQyM3csOa0dI9Y8o3DnWqeeD2+eJ8nEErkVkDVq2ucybRRgU7RbpF/yUkDF5KLbhtrzVgGet7P3bTv3FPGqVMfGWMZzWMJybZrcc6ESNDZMy5FU/J6lF2zbcDsNRW215zxYYvqcgYxwoZcHWtAB9F3y/VQC2t7DFwVpjalq/rm4K5ETHPrDFUdrwY7DXpX7wOu7w0ZA7C3Nho242jwm6dajSjWrYHEvBrjDMiTb7OKKfQw9jWQ/rhdE3cZ+MHTsukYjXXyigCvADyZHuWaC1G9FPSKWPGQNRh4P+6Z+NKblpz9Byw3KpnGYSHXgU0SJ+wTKLSivymfLU8vwBUvQ70epjUH6wvmDiP/gWLhJfVTosW6p6iLC8Qc=
provider: heroku
app: probot-sabrimarz
