sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: EGO/LbTcSfuCAPNnI4XGExaW4SCe5PykGzOjc0nu1DY1UMOt4x0v0GssKtuso361vlsIR1nQvW0niusRhlMiVbRrZxxtmwT5GbNP8aT/CV3cVFzdwTRSP+nXdqk8VaWDN3//se7SuQN56lHrXOY1qfvj0wSn29wN6rMls6e06xVDfRaD8AOIVOA5MmKwPT24tzkFVzWhbrYB7HgMDZABt1cR6h45J3QBQiHE32nxjgOfGYgkzUKEOAYftoEIeQzDYZG4qsiSrUUSvvHXAGeu2p21eSma8LC0jzTA5jlpy1ZBpe5COV96VJRWiTFWBU05m4/GaRpwbJbMPPywA4NZkB2bfs3gDCEYh4s1XBTm7szwirUvRugxqy9H93byKbmj+2ddwGVl20iPPDRwfUquw8QBxlHFFiTwZt74dqmmkjmhOosvPpo31BeAMhEZF8PDAVALWj8kVkLkRx8QnTsnH9WPGpvvr1RfCKocvz0NF4NGZPwIO++J3lhCFeuUKYqsnHHkvwgM5TNqDaC+5QJk/ASXhjj0pRHN+Y2uWHAGOBUi7knMpHsNvVpNBb5xS9LPNPV5g4aF4ixRc+d9DhOm0/mAV2uiWYhiYXb4ai/BUW3lKSwxtlFFsOeRh63db26MMn1c8yx8dmT1xMUnkZ97WRbFfQshx16D0QsJiUKohLI=
  on: heroku_production
  app: probot-ypereiro
#test change in heroku_deploy
#change 2
#another changes
